// <auto-generated />
using System;
using FitnesTracker;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace main.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FitnesTracker.CustomProgram", b =>
                {
                    b.Property<int>("CustomProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomProgramId"));

                    b.Property<int?>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("CustomProgramId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("CreatorUserId");

                    b.ToTable("CustomPrograms");
                });

            modelBuilder.Entity("FitnesTracker.CustomProgramExercise", b =>
                {
                    b.Property<int>("CustomProgramId")
                        .HasColumnType("integer");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer");

                    b.HasKey("CustomProgramId", "ExerciseId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("CustomProgramExercises");
                });

            modelBuilder.Entity("FitnesTracker.CustomProgramUser", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("integer");

                    b.Property<int>("CustomProgramId")
                        .HasColumnType("integer");

                    b.HasKey("IdUser", "CustomProgramId");

                    b.HasIndex("CustomProgramId");

                    b.ToTable("CustomProgramUsers");
                });

            modelBuilder.Entity("FitnesTracker.Exercise", b =>
                {
                    b.Property<int>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExerciseId"));

                    b.Property<int?>("CustomProgramId")
                        .HasColumnType("integer");

                    b.Property<int>("MuscleGroup")
                        .HasColumnType("integer");

                    b.Property<int?>("Reps")
                        .HasColumnType("integer");

                    b.Property<int?>("Sets")
                        .HasColumnType("integer");

                    b.Property<int?>("StandardProgramProgramId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("ExerciseId");

                    b.HasIndex("CustomProgramId");

                    b.HasIndex("StandardProgramProgramId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("FitnesTracker.StandardProgram", b =>
                {
                    b.Property<int>("ProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProgramId"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WorkoutType")
                        .HasColumnType("integer");

                    b.HasKey("ProgramId");

                    b.ToTable("StandardPrograms");
                });

            modelBuilder.Entity("FitnesTracker.StandardProgramExercise", b =>
                {
                    b.Property<int>("ProgramId")
                        .HasColumnType("integer");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer");

                    b.HasKey("ProgramId", "ExerciseId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("StandardProgramExercises");
                });

            modelBuilder.Entity("FitnesTracker.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<bool>("Author")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("EmailConfirmationToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EmailTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Lastname")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FitnesTracker.UserStandardProgram", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("integer");

                    b.Property<int>("ProgId")
                        .HasColumnType("integer");

                    b.HasKey("IdUser", "ProgId");

                    b.HasIndex("ProgId");

                    b.ToTable("UserStandardPrograms");
                });

            modelBuilder.Entity("FitnesTracker.WorkoutExerciseSet", b =>
                {
                    b.Property<int>("WorkoutExerciseSetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WorkoutExerciseSetId"));

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer");

                    b.Property<int>("Reps")
                        .HasColumnType("integer");

                    b.Property<int>("Sets")
                        .HasColumnType("integer");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.Property<int>("WorkoutSessionId")
                        .HasColumnType("integer");

                    b.HasKey("WorkoutExerciseSetId");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutSessionId");

                    b.ToTable("WorkoutExerciseSets");
                });

            modelBuilder.Entity("FitnesTracker.WorkoutSession", b =>
                {
                    b.Property<int>("WorkoutSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WorkoutSessionId"));

                    b.Property<int?>("CustomProgramId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("StandardProgramId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("WorkoutSessionId");

                    b.HasIndex("CustomProgramId");

                    b.HasIndex("StandardProgramId");

                    b.HasIndex("UserId");

                    b.ToTable("WorkoutSessions");
                });

            modelBuilder.Entity("FitnesTracker.CustomProgram", b =>
                {
                    b.HasOne("FitnesTracker.User", null)
                        .WithMany()
                        .HasForeignKey("CreatorId");

                    b.HasOne("FitnesTracker.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorUserId");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("FitnesTracker.CustomProgramExercise", b =>
                {
                    b.HasOne("FitnesTracker.CustomProgram", "CustomProgram")
                        .WithMany()
                        .HasForeignKey("CustomProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnesTracker.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomProgram");

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("FitnesTracker.CustomProgramUser", b =>
                {
                    b.HasOne("FitnesTracker.CustomProgram", "CustomProgram")
                        .WithMany()
                        .HasForeignKey("CustomProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnesTracker.User", "User")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomProgram");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnesTracker.Exercise", b =>
                {
                    b.HasOne("FitnesTracker.CustomProgram", null)
                        .WithMany("Exercises")
                        .HasForeignKey("CustomProgramId");

                    b.HasOne("FitnesTracker.StandardProgram", null)
                        .WithMany("Exercises")
                        .HasForeignKey("StandardProgramProgramId");
                });

            modelBuilder.Entity("FitnesTracker.StandardProgramExercise", b =>
                {
                    b.HasOne("FitnesTracker.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnesTracker.StandardProgram", "StandardProgram")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("StandardProgram");
                });

            modelBuilder.Entity("FitnesTracker.UserStandardProgram", b =>
                {
                    b.HasOne("FitnesTracker.User", "User")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnesTracker.StandardProgram", "StandardProgram")
                        .WithMany()
                        .HasForeignKey("ProgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StandardProgram");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnesTracker.WorkoutExerciseSet", b =>
                {
                    b.HasOne("FitnesTracker.Exercise", "Exercise")
                        .WithMany("WorkoutExerciseSets")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnesTracker.WorkoutSession", "WorkoutSession")
                        .WithMany("WorkoutExerciseSets")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("FitnesTracker.WorkoutSession", b =>
                {
                    b.HasOne("FitnesTracker.CustomProgram", "CustomProgram")
                        .WithMany()
                        .HasForeignKey("CustomProgramId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FitnesTracker.StandardProgram", "StandardProgram")
                        .WithMany()
                        .HasForeignKey("StandardProgramId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FitnesTracker.User", "User")
                        .WithMany("WorkoutSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomProgram");

                    b.Navigation("StandardProgram");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnesTracker.CustomProgram", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("FitnesTracker.Exercise", b =>
                {
                    b.Navigation("WorkoutExerciseSets");
                });

            modelBuilder.Entity("FitnesTracker.StandardProgram", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("FitnesTracker.User", b =>
                {
                    b.Navigation("WorkoutSessions");
                });

            modelBuilder.Entity("FitnesTracker.WorkoutSession", b =>
                {
                    b.Navigation("WorkoutExerciseSets");
                });
#pragma warning restore 612, 618
        }
    }
}
